#!/bin/bash
# kb-index.sh
# Auto-generate kb/index.md — a content catalog of every KB file, organized by
# type and category, with one-line summaries for scanning.
#
# Per Karpathy's llm-wiki pattern: this is the "what's in the wiki" entry point.
# Read this first when you don't know which file to read.
#
# Usage: bash scripts/kb-index.sh
# Output: writes/overwrites kb/index.md

set -euo pipefail

KB_DIR="$HOME/Documents/Tasks/kb"

python3 <<'EOF'
import os
import re
from pathlib import Path
from datetime import datetime

KB_DIR = Path(os.path.expanduser("~/Documents/Tasks/kb"))
INDEX = KB_DIR / "index.md"

def parse_frontmatter(text):
    """Extract YAML frontmatter as a dict (loose regex parse, no pyyaml needed)."""
    m = re.match(r'---\n(.*?)\n---\n', text, re.DOTALL)
    if not m:
        return {}, text
    body = text[m.end():]
    fm_text = m.group(1)
    fm = {}
    for line in fm_text.splitlines():
        if ':' not in line:
            continue
        k, _, v = line.partition(':')
        v = v.strip()
        # Handle list values like [a, b, c]
        if v.startswith('[') and v.endswith(']'):
            v = [x.strip() for x in v[1:-1].split(',') if x.strip()]
        else:
            v = v.strip().strip('"').strip("'")
        fm[k.strip()] = v
    return fm, body

def first_summary_line(body):
    """Get the first meaningful line after the # heading — short summary."""
    lines = body.splitlines()
    after_heading = False
    for line in lines:
        line = line.strip()
        if line.startswith('# '):
            after_heading = True
            continue
        if not after_heading:
            continue
        if not line or line.startswith('#') or line.startswith('---'):
            continue
        # Truncate to ~120 chars
        if len(line) > 120:
            line = line[:117] + '...'
        return line
    return ''

def load_kb():
    """Return list of (path, frontmatter, summary)."""
    items = []
    for sub in ['people', 'companies', 'themes', 'decisions']:
        d = KB_DIR / sub
        if not d.is_dir():
            continue
        for f in sorted(d.glob('*.md')):
            if f.name == 'README.md':
                continue
            text = f.read_text()
            fm, body = parse_frontmatter(text)
            summary = first_summary_line(body)
            items.append((f, fm, summary))
    return items

def fmt_relevant(fm):
    rel = fm.get('relevant_for', '')
    if isinstance(rel, list):
        return ', '.join(rel)
    return str(rel) if rel else ''

def fmt_status(fm):
    s = fm.get('status', '')
    if s and s not in ('active',):
        return f' · _{s}_'
    return ''

def fmt_last_touch(fm):
    lt = fm.get('last_touch', '')
    return f' · last touch {lt}' if lt else ''

items = load_kb()

# Group by type, then within type by relevant_for (for people/companies)
out = []
out.append("# Knowledge Base Index")
out.append("")
out.append("*Auto-generated by `scripts/kb-index.sh`. Do not edit by hand.*")
out.append(f"*Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}*")
out.append("")
out.append(f"**{len(items)} entries** across people, companies, themes, decisions.")
out.append("")
out.append("---")
out.append("")

# People — group by relevant_for
people = [i for i in items if i[1].get('type') == 'person']
if people:
    out.append("## People")
    out.append("")
    by_relevant = {}
    for f, fm, summary in people:
        key = fmt_relevant(fm) or '(unspecified)'
        by_relevant.setdefault(key, []).append((f, fm, summary))
    for key in sorted(by_relevant.keys()):
        out.append(f"### relevant_for: {key}")
        out.append("")
        for f, fm, summary in sorted(by_relevant[key], key=lambda x: x[1].get('name', x[0].name)):
            name = fm.get('name', f.stem)
            firm = fm.get('firm', '')
            role = fm.get('role', '')
            meta = []
            if firm:
                meta.append(firm)
            if role:
                meta.append(role)
            meta_str = f" — {', '.join(meta)}" if meta else ''
            rel_path = f.relative_to(KB_DIR.parent)
            line = f"- [{name}]({rel_path}){meta_str}{fmt_status(fm)}{fmt_last_touch(fm)}"
            if summary:
                out.append(line)
                out.append(f"  - {summary}")
            else:
                out.append(line)
        out.append("")

# Companies
companies = [i for i in items if i[1].get('type') == 'company']
if companies:
    out.append("## Companies")
    out.append("")
    for f, fm, summary in sorted(companies, key=lambda x: x[1].get('name', x[0].name)):
        name = fm.get('name', f.stem)
        rel = fmt_relevant(fm)
        meta = []
        if rel:
            meta.append(f"relevant_for: {rel}")
        rship = fm.get('relationship', '')
        if rship:
            meta.append(rship)
        meta_str = f" — {', '.join(meta)}" if meta else ''
        rel_path = f.relative_to(KB_DIR.parent)
        line = f"- [{name}]({rel_path}){meta_str}{fmt_status(fm)}{fmt_last_touch(fm)}"
        if summary:
            out.append(line)
            out.append(f"  - {summary}")
        else:
            out.append(line)
    out.append("")

# Themes
themes = [i for i in items if i[1].get('type') == 'theme']
if themes:
    out.append("## Themes")
    out.append("")
    for f, fm, summary in sorted(themes, key=lambda x: x[1].get('title', x[0].name)):
        title = fm.get('title', fm.get('name', f.stem))
        rel_path = f.relative_to(KB_DIR.parent)
        line = f"- [{title}]({rel_path}){fmt_status(fm)}"
        if summary:
            out.append(line)
            out.append(f"  - {summary}")
        else:
            out.append(line)
    out.append("")

# Decisions
decisions = [i for i in items if i[1].get('type') == 'decision']
if decisions:
    out.append("## Decisions")
    out.append("")
    for f, fm, summary in sorted(decisions, key=lambda x: x[0].name, reverse=True):
        title = fm.get('title', f.stem)
        date = fm.get('date', '')
        rel_path = f.relative_to(KB_DIR.parent)
        line = f"- [{title}]({rel_path}) — {date}{fmt_status(fm)}"
        if summary:
            out.append(line)
            out.append(f"  - {summary}")
        else:
            out.append(line)
    out.append("")

INDEX.write_text('\n'.join(out))
print(f"Wrote {INDEX} ({len(items)} entries)")
EOF
